Anus2_august-main/AnusCopy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),

]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

Anus2_august-main/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.DiscussionListView.as_view(), name='discussion_list'),
    path('create/', views.DiscussionCreateView.as_view(), name='discussion_create'),
    path('<int:pk>/', views.DiscussionDetailView.as_view(), name='discussion_detail'),
    path('<int:pk>/comment/', views.comment_create, name='comment_create'),

]

Anus2_august-main/templates/default.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>
<header class="header">
    <a href="{% url 'books_list' %}"><img src="{% static 'images/Anus-1.png' %}" height=75px; width=100px;></a>
    <nav class="header-nav">
        <ul class="header-menu-list">

            <li><a href="#">Books</a></li>
            <li><a href={% url 'forum:discussion_list' %}>Discussions</a></li>
            <li><a href="#">Contents</a></li>
            <li><a href="{% url 'library' username=request.user.username %}">My Library</a></li>

        </ul>
    </nav>
            <li><a href={% url 'book_create' %}>AddBookReal</a></li>
            <li><a href={% url 'create_series' %}>CreateSeries</a></li>
            <li><a href="{% url 'notifications' %}">notifications</a></li>
    <form method="get">
            <input name="header-search" placeholder="Search" type="search" size="30">
    </form>
</header>

 {% block content %}
 {% endblock content %}