Anus2_august-main/AnusCopy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),

]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

Anus2_august-main/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.DiscussionListView.as_view(), name='discussion_list'),
    path('create/', views.DiscussionCreateView.as_view(), name='discussion_create'),
    path('<int:pk>/', views.DiscussionDetailView.as_view(), name='discussion_detail'),
    path('<int:pk>/comment/', views.comment_create, name='comment_create'),

]

Anus2_august-main/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('settings/main_settings', views.settings, name='main_settings'),
    path('follow', views.follow, name='follow'),
    path('logout', views.logout, name='logout'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('add_to_library/<int:book_id>/<str:category>/', views.add_to_library, name='add_to_library'),
    path('<str:username>/library/',views.my_library_view, name='library'),
    path('delete_book/<int:book_id>/', views.delete_book_from_library, name='delete_book_from_library'),
    path('get_library_content/<str:username>/', views.get_library_content, name='get_library_content'),
    path('get_comments_content/<str:username>/', views.get_comments_content, name='get_comments_content'),
    path('get_achievements_content/<str:username>/', views.get_achievements_content, name='get_achievements_content'),
    path('get_profile_content/<str:username>/', views.get_profile_content, name='get_profile_content'),
    path('achievements/', views.achievements, name='achievements'),
    path('settings/book_settings/<int:book_id>/', views.book_settings, name='book_settings'),
    path('upload_illustration/', views.upload_illustration, name='upload_illustration'),
    path('upload_trailer/', views.upload_trailer, name='upload_trailer'),
    path('delete_illustration/<int:illustration_id>/', views.delete_illustration, name='delete_illustration'),
    path('delete_trailer/<int:trailer_id>/', views.delete_trailer, name='delete_trailer'),
    path('settings/web_settings/', views.web_settings, name='web_settings'),
    path('main_settings/', views.main_settings, name='main_settings'),
    path('settings/notifications/', views.settings_notifications, name='settings-notifications'),
    path('settings/privacy/', views.privacy_settings, name='settings-privacy'),
    path('settings/blacklist/', views.blacklist, name='blacklist'),
    path('settings/reviews_settings/', views.reviews, name='reviews_settings'),
    path('settings/social/', views.social, name='social'),
    path('settings/my_books/', views.my_books, name='my_books'),
    path('settings/my_series/', views.my_series, name='my_series'),
    path('settings/my_account/', views.my_account, name='my_account'),
    path('settings/security/', views.security, name='security'),
    path('settings/purchase_history/', views.purchase_history, name='purchase_history'),
    path('blacklist/<str:username>/add/', views.add_to_blacklist, name='add_to_blacklist'),
    path('blacklist/<str:username>/remove/', views.remove_from_blacklist, name='remove_from_blacklist'),
    path('blacklist/', views.blacklist, name='blacklist'),
    path('notifications/unread_count/', views.notification_count, name='unread_notification_count'),
    path('notifications/notifications/', views.notifications, name='notifications'),
    path('notifications/read/<int:notification_id>/', views.read_notification, name='read_notification'),
    path('conversation/<int:user_id>/', views.conversation_view, name='conversation'),
    path('messages_list/', views.messages_list_view, name='messages_list'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('delete_conversation/<int:user_id>/', views.delete_conversation, name='delete_conversation'),


    # ...add more paths for the other settings
    # ...
    ]

Anus2_august-main/store/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from datetime import timedelta

User = get_user_model()


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Series(models.Model):
    name = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    description = models.TextField(default='')
    author_remark = models.TextField(default='')
    series_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Book(models.Model):
    TYPE_CHOICES = (
        ('epic_novel', 'Epic Novel'),
        ('novel', 'Novel'),
        ('short_story', 'Short Story'),
        ('short_story_collection', 'Short Story Collection'),
        ('poem_collection', 'Poem Collection'),
    )

    STATUS_CHOICES = (
        ('in_progress', 'In Progress'),
        ('finished', 'Finished'),
        ('draft', 'Draft'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    co_author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                  related_name='coauthored_books')
    co_author2 = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                  related_name='coauthored_books2')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    coverpage = models.ImageField(upload_to='static/images/coverpage', default='default_book_img.png')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField()
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)
    display_comments = models.BooleanField(default=True)
    book_type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='in_progress')
    series = models.ForeignKey(Series, on_delete=models.SET_NULL, null=True, blank=True)
    abstract = models.CharField(max_length=500, blank=True)
    author_remark = models.TextField(blank=True)
    is_adult = models.BooleanField(default=False)
    rating = models.IntegerField(default=0)
    views_count = models.PositiveIntegerField(default=0)

    def increase_views_count(self, user=None):
        if user is None:
            self.views_count += 1
            self.save()
        else:
            last_view = BookView.objects.filter(book=self, user=user).order_by('-timestamp').first()
            if not last_view or (timezone.now() - last_view.timestamp) > timedelta(days=1):
                self.views_count += 1
                self.save()
                BookView.objects.create(book=self, user=user)

    def save(self, *args, **kwargs):
        if self.series_id == '':  # If "No Series" was selected in the form...
            self.series = None
        super().save(*args, **kwargs)

    def toggle_comments_reviews(self):
        # Logic to toggle between comments and reviews
        self.display_comments = not self.display_comments
        self.save()


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='chapters')
    title = models.CharField(max_length=200, blank=True)  # This will hold the "Chapter X" title
    additional_title = models.CharField(max_length=200, blank=True)  # This is for the additional title
    content = models.TextField()

    def save(self, *args, **kwargs):
        if not self.title:
            # If the title is not provided, generate it automatically
            # Get the number of existing chapters for the book
            num_chapters = Chapter.objects.filter(book=self.book).count()
            self.title = f"Chapter {num_chapters + 1}"

        super().save(*args, **kwargs)


class BookView(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    views_count = models.PositiveIntegerField(default=0)
    last_viewed = models.DateTimeField(null=True, blank=True)
    rating = models.IntegerField(default=0)

    def count_likes(self):
        return self.likes.count()

    def count_dislikes(self):
        return self.dislikes.count()

    def increase_views_count(self, user):
        if not self.last_viewed or (timezone.now() - self.last_viewed) > timedelta(days=1):
            self.views_count += 1
            self.last_viewed = timezone.now()
            self.save()
            return True
        return False

    def save(self, *args, **kwargs):
        genre = self.book.genre
        name = f"Review for a {genre} {self.book.name} - {self.book.author}"
        self.name = name
        super().save(*args, **kwargs)


class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='store_comments')
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    def count_likes(self):
        return self.likes.count()

    def count_dislikes(self):
        return self.dislikes.count()


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['comment', 'user']  # To prevent a user from liking a comment multiple times


class CommentDislike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='dislikes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['comment', 'user']  # To prevent a user from disliking a comment multiple times


class ReviewLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='review_likes')

    class Meta:
        unique_together = ['review', 'user']


class ReviewDislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='review_dislikes')

    class Meta:
        unique_together = ['review', 'user']


class BookUpvote(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='upvotes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['book', 'user']  # To prevent a user from upvoting a book multiple times


class BookDownvote(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='downvotes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['book', 'user']  #

Anus2_august-main/users/forms.py
from django import forms
from .models import Illustration, Trailer, Profile, WebPageSettings, Message
import datetime


class UploadIllustrationForm(forms.ModelForm):
    class Meta:
        model = Illustration
        fields = ('image',)


class UploadTrailerForm(forms.ModelForm):
    class Meta:
        model = Trailer
        fields = ('link', )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'bio', 'profileimg']


class WebPageSettingsForm(forms.ModelForm):
    class Meta:
        model = WebPageSettings
        fields = ['about', 'date_of_birth', 'status', 'profile_url', 'website', 'email', 'facebook', 'instagram', 'twitter', 'display_dob_option']
        widgets = {
            'date_of_birth': forms.SelectDateWidget(years=range(1900, datetime.date.today().year+1))
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text',]

Anus2_august-main/users/templates/settings/blacklist.html
<h1> BLACKLIST </h1>

{% block content %}

    {% for user in blacklisted_users %}
        <div>
            <h3>{{ user.username }}</h3>
            <form method="post" action="{% url 'remove_from_blacklist' username=user.username %}">
                {% csrf_token %}
                <input type="submit" value="Remove from blacklist">
            </form>
        </div>
    {% empty %}
        <p>You have no users in your blacklist.</p>
    {% endfor %}
{% endblock %}

Anus2_august-main/users/templates/settings/book_settings.html
{% load youtube_embed_url %}
{% load static %}
<!-- rest of your HTML -->

<html>
<head>
    <title>Book Settings</title>
</head>
<body>
<link rel="stylesheet" href="{% static 'css/illustration_image_delete.css' %}">
<h2>Book Settings</h2>

<button id="settingsBtn">Settings</button>
<button id="textBtn">Text</button>
<button id="illustrationsBtn">Illustrations</button>
<button id="salesBtn">Sales</button>

<div id="settings">
    <h3>Settings</h3>
{% block content %}
<link rel="stylesheet" href="{% static 'css/book_create.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <label for="name">Book Name:</label>
            {{ book_form.name }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="bookType">Type of book:</label>
                <select name="book_type">
                {% for type, display_name in book_type_form.fields.book_type.choices %}
                <option value="{{ type }}">{{ display_name }}</option>
                {% endfor %}
              </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="co_author">Co-Author 1:</label>
            {{ book_form.co_author }}
        </div>
        <div class="col">
            <label for="co_author2">Co-Author 2:</label>
            <!-- You may need to adjust the field name here -->
            {{ book_form.co_author2 }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="genre">Genre:</label>
            {{ book_form.genre }}
        </div>

        <div class="col">
            <label for="series">Series:</label>
              <select id="series" name="series">
                <option value="" {% if not book.series %}selected{% endif %}>No Cycle</option>
                {% for series in user_series %}
                    <option value="{{ series.id }}" {% if book.series.id == series.id %}selected{% endif %}>{{ series.name }}</option>
                {% endfor %}
            </select>

        </div>

    </div>
    <div class="row">
        <div class="col">
            <label for="genre2">Genre 2:</label>
            <!-- You may need to adjust the field name here -->
            {{ book_form.genre2 }}
        </div>
        <div class="col">
            <label for="genre3">Genre 3:</label>
            <!-- You may need to adjust the field name here -->
            {{ book_form.genre3 }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="abstract">Abstract:</label>
            {{ book_form.abstract }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="author_remark">Author's remark:</label>
            {{ book_form.author_remark }}
        </div>
    </div>
    <div class="row">
        <div class="col">
             <input type="checkbox" id="display_paragraphs_indent" name="display_paragraphs_indent">
                <label for="display_paragraphs_indent">Display all paragraphs with an indent</label>
        </div>
        <div class="col">
            <input type="checkbox" id="copyright_protection" name="copyright_protection">
            <label for="copyright_protection">Copyright protection</label>
        </div>
        <div class="col">
            {{ book_form.is_adult }}<label for="is_adult">Is adult?</label>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="who_can_see">Who can see the book?</label>
              <select id="who_can_see" name="who_can_see">
                <option value="nobody">Nobody</option>
                <option value="anybody">Anybody</option>
                <option value="friends">Friends</option>
                <option value="followers">Followers</option>
              </select>
        </div>
        <div class="col">
            <label for="who_can_download">Who can download the book?</label>
              <select id="who_can_download" name="who_can_download">
                <option value="nobody">Nobody</option>
                <option value="anybody">Anybody</option>
                <option value="friends">Friends</option>
                <option value="followers">Followers</option>
              </select>
        </div>
        <div class="col">
             <label for="who_can_comment">Who can leave a comment on the book's page?</label>
                  <select id="who_can_comment" name="who_can_comment">
                    <option value="nobody">Nobody</option>
                    <option value="anybody">Anybody</option>
                    <option value="friends">Friends</option>
                    <option value="followers">Followers</option>
                  </select>
        </div>


    </div>
<div class="row">
    <div class="col">
        <label for="price">Price:</label>
        {{ book_form.price }}
    </div>
</div>
<div class="row">
    <div class="col">
        <label for="coverpage">Cover Page:</label>
        {{ book_form.coverpage }}
    </div>
</div>
<div class="row">
    <div class="col">
        <label for="description">Description:</label>
        {{ book_form.description }}
    </div>
</div>
<div class="row">
    <div class="col">
        <label for="status">Status:</label>
        {{ book_form.status }}
    </div>
</div>
    <button type="submit">Save</button>
</form>


{% endblock content %}
</div>

<div id="text" style="display: none;">
    <h3>Text</h3>
    <h4>This book is in drafts and only you can see it.
    To have the ability to publish the book, it is necessary to publish at least one part of it.</h4>
    <div class="row">
        <div class="col">
            <label for="status">Status:</label>
            {{ book_form.status }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Publish</button>
            <select id="publishScope" class="form-control">
                <option>Current Chapter</option>
                <option>The Whole Book</option>
            </select>
        </div>
    </div>
        <form method="post">
            {% csrf_token %}
            <h2>{{ chapter.title }} Chapter 1 : {{ chapter.additional_title }}</h2>
            {{ chapter_form.as_p }}
            <button type="submit" class="btn btn-primary">Publish</button>
        </form>


</div>

<div id="illustrations" style="display: none;">
    <h3>Illustrations</h3>
        <p>Here you can upload illustrations for your book and provide a link to a book trailer.
        The following formats are allowed: jpg, jpeg, png. Up to 30 files can be uploaded. The maximum file size is 5.0 MB.
        The uploaded illustration must not violate copyright and related rights.</p>
    <h2>Upload Illustration:</h2>
            <form action="{% url 'upload_illustration' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="image" required>
                <button type="submit">Upload Illustration</button>
            </form>


        <h2>Illustrations:</h2>

            {% if illustrations %}
                {% for illustration in illustrations %}
                    <div class="image-container">
                    <img src="{{ illustration.image.url }}" style="max-width: 400px; max-height: 400px;">
                     <form class="delete-form" action="{% url 'delete_illustration' illustration.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                    </div>
                {% endfor %}
            {% else %}
                <p>You have not uploaded any illustration yet.</p>
            {% endif %}
            <h2>Trailers:</h2>

                <form action="{% url 'upload_trailer' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Upload Trailer Link</button>
                </form>

                {% for trailer in trailers %}
                    <iframe width="560" height="315" src="{{ trailer.link|convert_to_embed_url }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <form action="{% url 'delete_trailer' trailer.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Delete Trailer</button>
                    </form>
                {% empty %}
                    <p>No trailers uploaded yet.</p>
                {% endfor %}





    <p id="fileSizeWarning" style="display: none; color: red;">File size must be less than 5 MB.</p>



</div>

<div id="sales" style="display: none;">
    <h3>Sales</h3>
    <!-- Add sales features here -->
</div>

<script>
document.getElementById('settingsBtn').onclick = function() {
    hideAll();
    document.getElementById('settings').style.display = 'block';
};

document.getElementById('textBtn').onclick = function() {
    hideAll();
    document.getElementById('text').style.display = 'block';
};

document.getElementById('illustrationsBtn').onclick = function() {
    hideAll();
    document.getElementById('illustrations').style.display = 'block';
};

document.getElementById('salesBtn').onclick = function() {
    hideAll();
    document.getElementById('sales').style.display = 'block';
};

document.getElementById('fileInput').onchange = function() {
    var fileSize = this.files[0].size / 1024 / 1024; // in MB
    if (fileSize > 5) {
        document.getElementById('fileSizeWarning').style.display = 'block';
        this.value = '';
    } else {
        document.getElementById('fileSizeWarning').style.display = 'none';
    }
};

function hideAll() {
    document.getElementById('settings').style.display = 'none';
    document.getElementById('text').style.display = 'none';
    document.getElementById('illustrations').style.display = 'none';
    document.getElementById('sales').style.display = 'none';
}
</script>

</body>
</html>

Anus2_august-main/users/templates/settings/display_illustrations.html
{% for illustration in illustrations %}
    <img src="{{ illustration.image.url }}">
{% endfor %}

Anus2_august-main/users/templates/settings/main_settings.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Settings</title>
    <!-- Your styles and scripts here -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    <div class="sidebar">
        <button class="settings-toggle" id="webpage-settings-toggle">WebPage Settings</button>
        <button class="settings-toggle" id="notifications-toggle">Notifications</button>
        <button class="settings-toggle" id="privacy-toggle">Privacy Settings</button>
        <button class="settings-toggle" id="blacklist-toggle">Blacklist</button>
        <button class="settings-toggle" id="reviews-toggle">Reviews</button>
        <button class="settings-toggle" id="social-toggle">Social</button>
        <button class="settings-toggle" id="my_books-toggle">My Books</button>
        <button class="settings-toggle" id="my_series-toggle">My Series</button>
        <button class="settings-toggle" id="my_account-toggle">My Account</button>
        <button class="settings-toggle" id="security-toggle">Security</button>
        <button class="settings-toggle" id="purchase_history-toggle">Purchase History</button>
    </div>

    <div class="content-area" id="settings-content-area">
        {% if current_tab == "settings/web_settings.html" %}
            {% include "settings/web_settings.html" %}
        {% elif current_tab == "notifications" %}
            {% include "settings/notifications.html" %}
        {% elif current_tab == "privacy" %}
            {% include "settings/privacy.html" %}
        {% elif current_tab == "blacklist" %}
            {% include "settings/blacklist.html" %}
        {% elif current_tab == "reviews" %}
            {% include "settings/reviews_settings.html" %}
        {% elif current_tab == "social" %}
            {% include "settings/social.html" %}
        {% elif current_tab == "my_books" %}
            {% include "settings/my_books.html" %}
        {% elif current_tab == "my_series" %}
            {% include "settings/my_series.html" %}
        {% elif current_tab == "my_account" %}
            {% include "settings/my_account.html" %}
        {% elif current_tab == "security" %}
            {% include "settings/security.html" %}
        {% elif current_tab == "purchase_history" %}
            {% include "settings/purchase_history.html" %}
        {% else %}
            <!-- Default content if no tab is selected -->
            <p>Please select a tab from the sidebar.</p>
        {% endif %}
    </div>
</body>
<script src="{% static 'js/settings.js' %}"></script>
</html>

Anus2_august-main/users/templates/settings/my_account.html
<h1> MY ACCOUNT </h1>

Anus2_august-main/users/templates/settings/my_books.html
<h1> MY BOOKS </h1>
{% block content %}
{% for book in my_authored_books %}
    <div>
       <img src="{{ book.coverpage.url }}" alt="" style='width: 168px; height: 236px'>
        <h2>{{ book.name }}</h2>
        {{ book.author }}
        {{ book.status }}
        Last Update: {{ book.updated|date:"F d, Y H:i" }}
        Is adult? : {{ book.is_adult }}
        Book Series: {{ book.series }}
        Comments: {{ book.comment_count }}
        Reviewed: {{ book.review_count }}
        Rating: {{ book.rating }}
        In Library Users: {{ book.in_library_users }}
        Number of Views: {{ book.views_count }}
        Characters in Chapters: {{ book.character_count }}

        {% if book.series %}
            Book Series: <a href="{% url 'series_detail' book.series.id %}">{{ book.series.name }}</a>
        {% else %}
            No Series
        {% endif %}


       <a href = '{% url 'book_settings' book.id %}'><button class="settingsBtn" data-book-id="{{book.id}}" data-initial="{{ show_settings  }}">Settings</button></a>
       <a href = '{% url 'book_settings' book.id %}'><button class="textBtn" data-book-id="{{book.id}}" data-initial="{{ show_text  }}">Text</button></a>
       <a href = '{% url 'book_detail' book.id %}'><button class="textBtn" data-book-id="{{book.id}}">Book's Page</button></a>

    </div>
{% endfor %}
<script>
  let settingsButtons = document.querySelectorAll('.settingsBtn');
  let textButtons = document.querySelectorAll('.textBtn');

  console.log('Number of settings buttons:', settingsButtons.length);
  console.log('Number of text buttons:', textButtons.length);

  settingsButtons.forEach(function(button) {
    button.addEventListener('click', function() {
      let bookId = button.getAttribute('data-book-id');
      console.log('Settings button clicked for book ID:', bookId);
      hideAll(bookId);
      document.getElementById('settings' + bookId).style.display = 'block';
    });
  });

  textButtons.forEach(function(button) {
    button.addEventListener('click', function() {
      let bookId = button.getAttribute('data-book-id');
      console.log('Text button clicked for book ID:', bookId);
      hideAll(bookId);
      document.getElementById('text' + bookId).style.display = 'block';
    });
  });

function hideAll(bookId) {
  console.log('Hiding all sections for book ID:', bookId);
  document.getElementById('settings' + bookId).style.display = 'none';
  document.getElementById('text' + bookId).style.display = 'none';
}
</script>

{% endblock %}

Anus2_august-main/users/templates/settings/my_series.html
<h1> MY SERIES </h1>

{% for series in user_series %}
    <div>
        <a href = '{% url 'series_update' series.id %}'><button><h2>{{ series.name }}</h2></button></a>
        <p>Description: {{ series.description }}</p>
        <p>Author's remark: {{ series.author_remark }}</p>
        {% if series.series_finished %}
            <p>Series finished</p>
        {% else %}
            <p>Series still on process</p>
        {% endif %}

        <h3>Books in this series:</h3>
        <ul>
            {% for book in series.book_set.all %}
                <li><a href="{% url 'book_detail' book.id %}">{{ book.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}

Anus2_august-main/users/templates/settings/purchase_history.html
<h1> PURCHASE HISTORY </h1>

Anus2_august-main/users/templates/settings/security.html
<h1> SECURITY </h1>

<h2>Change Password</h2>
<form method="POST" action="">
  {% csrf_token %}

  <label for="old_password">Current password:</label>
  <input type="password" name="old_password" required>

  <label for="new_password">New password:</label>
  <input type="password" name="new_password" required>

  <label for="confirm_password">Confirm new password:</label>
  <input type="password" name="confirm_password" required>

  <button type="submit" name="change_password">Save</button>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

Anus2_august-main/users/templates/settings/social.html
<h1> SOCIAL </h1>

<h1>Friends</h1>
{% for friend in friends %}
    <p>{{ friend.username }}</p>
{% endfor %}

<h1>Followers</h1>
{% for follower in followers %}
    <p>{{ follower.username }}</p>
{% endfor %}

<h1>Following</h1>
{% for followed in following %}
    <p>{{ followed.username }}</p>
{% endfor %}

Anus2_august-main/users/templates/settings/upload_illustration.html
<form action="{% url 'upload_illustration' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>